export const NEW_ADDRESS_REQUEST ='NEW_ADDRESS_REQUEST'
export const NEW_ADDRESS_SUCCESS ='NEW_ADDRESS_SUCCESS'
export const NEW_ADDRESS_FAIL ='NEW_ADDRESS_FAIL'

export const ADDRESS_REQUEST ='ADDRESS_REQUEST'
export const ADDRESS_SUCCESS ='ADDRESS_SUCCESS'
export const ADDRESS_FAIL ='ADDRESS_FAIL'

export const UPDATE_ADDRESS_REQUEST ='UPDATE_ADDRESS_REQUEST'
export const UPDATE_ADDRESS_SUCCESS ='UPDATE_ADDRESS_SUCCESS'
export const UPDATE_ADDRESS_FAIL ='UPDATE_ADDRESS_FAIL'


export const CLEAR_ERRORS ='CLEAR_ERRORS'