export const NEW_ORDER_REQUEST ='NEW_ORDER_REQUEST'
export const NEW_ORDER_SUCCESS ='NEW_ORDER_SUCCESS'
export const NEW_ORDER_FAIL ='NEW_ORDER_FAIL'

export const ORDERS_REQUEST ='ORDERS_REQUEST'
export const ORDERS_SUCCESS ='ORDERS_SUCCESS'
export const ORDERS_FAIL ='ORDERS_FAIL'

export const CLEAR_ERRORS ='CLEAR_ERRORS'